### ISSUE TITLE
c-data backgroundcolor not working

### ISSUE THREAD

**Issue by troveryor** [SalesforceLabs/LightningWebChartJS#29] opened 2021-01-12 18:49 UTC
## _Who_ is the bug affecting?
So far just me, working on a new feature in a scratch org and needed a charting option.

## _What_ is affected by this bug?
Presentation of charts is diminished by only showing markers/lines/fills in greyscale.

## _When_ does this occur?
Created a new LWC and included c-chart examples from the sample gallery in lightning-layout-items . 
On viewing the app, the charts render, but none of the colors are present, everything is grey.

## _Where_ on the platform does it happen?
In my LWC app.

## _How_ do we replicate the issue?
If I add any chart to my LWC and view, no colors are used.

## Expected behavior (i.e. solution)
The colors designated in the c-data backgroundcolor list get used in the chart 

## Other Comments
Here is the entirety of my LWC:
```
<template>
    <lightning-layout multiple-rows="false">
        <lightning-layout size="4">
            <div> put other cards here</div>
        </lightning-layout>
        <lightning-layout size="4">
            <c-chart type="doughnut" responsive="true">
                 <c-dataset labels='["OK", "WARNING", "CRITICAL", "UNKNOWN"]'>
                      <c-data label="# of Tomatoes" detail="[12, 19, 3, 5]" backgroundcolor='[
                           "rgba(14, 110, 206, 1)",
                           "rgba(45, 156, 237, 1)",
                           "rgba(104, 206, 238, 1)",
                           "rgba(150, 242, 238, 1)"
                          ]'></c-data>
                     </c-dataset>
                 <c-title text="Doughnut Chart"></c-title>
                 <c-legend position="left"></c-legend>
                 <c-arc-configuration bordercolor="rgba(7, 62, 146, 0.7)"></c-arc-configuration>
            </c-chart>
        </lightning-layout>
        <lightning-layout size="4">
        <c-chart type="bar" responsive="true" stylecss="position: relative; margin: auto;" events='["click"]'>
             <c-dataset labels='["Blue", "Orange", "Yellow", "Green", "Light Blue", "Purple"]'>
                  <c-data label="# of Votes" detail="[12, 19, 7, 9, 5, 15]" backgroundcolor='[
               "rgba(82, 183, 216, 0.2)",
               "rgba(225, 96, 50, 0.2)",
               "rgba(255, 176, 59, 0.2)",
               "rgba(84, 167, 123, 0.2)",
               "rgba(79, 210, 210, 0.2)",
               "rgba(226, 135, 178, 0.2)"
               ]' bordercolor='[
                "rgba(82, 183, 216, 1)",
                "rgba(225, 96, 50, 1)",
                "rgba(255, 176, 59, 1)",
                "rgba(84, 167, 123, 1)",
                "rgba(79, 210, 210, 1)",
                "rgba(226, 135, 178, 1)"
               ]' borderwidth="1"></c-data>
                 </c-dataset>
             <c-title text="Bar Chart"></c-title>
             <c-legend position="right"></c-legend>
             <c-animation duration="2000" easing="easeInBounce"> </c-animation>
             <c-cartesian-category-axis axis="x" position="top"></c-cartesian-category-axis>
        </c-chart>
    </lightning-layout>
    </lightning-layout>
</template>
```

**Comment by adburke** [comment] 2021-01-13 05:44
@troveryor 

I believe I saw this same thing. Placing the backgroundcolor's all on a single line and not breaking them up across multiple lines fixed the issue for me.

**Comment by troveryor** [comment] 2021-01-13 13:39
Thanks @adburke, can confirm that did resolve my issue.
Does pose a bit of an issue as prettier seems to want to format my JS code in a way that doesn't work.

**Comment by victorgz** [comment] 2021-01-13 14:07
Thanks a lot @adburke !! 🙌 

@troveryor as the issue is solved now, I will close it. Don't hesitate to reach out if you have any other question !

**Closed by victorgz** 2021-01-13 14:07 UTC
